In [2]:
import tensorflow as tf

In [3]:
print(tf.__version__)

2.8.0


In [15]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

In [16]:
print(tf.__version__)

2.8.0


In [17]:
hello = tf.constant("Hello")

In [18]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [19]:
world = tf.constant("world")

In [20]:
result = hello + world

In [21]:
result

<tf.Tensor 'add_2:0' shape=() dtype=string>

In [22]:
type(result)

tensorflow.python.framework.ops.Tensor

In [24]:
with tf.Session() as sess:
    result = sess.run(hello + world)

In [25]:
result

b'Helloworld'

In [26]:
tensor_1 = tf.constant(1)
tensor_2 = tf.constant(2)

In [27]:
type(tensor_1)

tensorflow.python.framework.ops.Tensor

In [30]:
tensor_1 + tensor_2

<tf.Tensor 'add_5:0' shape=() dtype=int32>

In [31]:
tensor_1 + tensor_2

<tf.Tensor 'add_6:0' shape=() dtype=int32>

In [32]:
sess

In [33]:
sess.close()

In [34]:
const = tf.constant(10)

In [35]:
fill_mat = tf.fill((4,4),10)

In [36]:
myzeros = tf.zeros((4,4))

In [37]:
myones = tf.ones((4,4))

In [39]:
myrandn = tf.random_normal((4,4), mean=0, stddev=0.5)

In [40]:
myrandu = tf.random_uniform((4,4), minval=0, maxval=1)

In [41]:
my_ops = [const, fill_mat, myzeros, myrandn, myrandu]

In [42]:
sess = tf.InteractiveSession()

In [47]:
for op in my_ops:
    print(sess.run(op), end="\n\n")

10

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[-0.5225579   0.5749281  -0.21288837 -0.8491075 ]
 [ 0.5001257  -0.24633884  0.326718    0.09639911]
 [ 0.20917264  0.23523894 -0.00345352 -0.20333907]
 [ 0.17728424  1.2723285  -0.24792685 -0.23196934]]

[[0.37425613 0.6627215  0.10348475 0.28698397]
 [0.37667668 0.7468393  0.96152115 0.27654636]
 [0.19665754 0.41457784 0.21228743 0.4038267 ]
 [0.46594584 0.8630805  0.3567288  0.3311981 ]]



In [48]:
for op in my_ops:
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[-0.11098483 -0.2720226  -0.21548478  0.05154473]
 [-0.58083886  0.14653276  0.03261496  0.56790054]
 [-0.530445    0.27778777  0.25306612  0.14541723]
 [-0.7894396   0.5901318   0.8499741  -0.32657444]]


[[0.77887666 0.1947416  0.07759714 0.7736887 ]
 [0.97077966 0.6015538  0.56905854 0.4934038 ]
 [0.44082808 0.05036461 0.88849425 0.6843935 ]
 [0.14693463 0.9091481  0.4153402  0.6739756 ]]




In [49]:
a = tf.constant([ [1,2],
                    [3,4]])

In [50]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [51]:
b  = tf.constant([[10],[100]])

In [52]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [53]:
result = tf.matmul(a, b)

In [54]:
result.eval()

array([[210],
       [430]])